# Headless Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: shoppinglist
spec:
  clusterIP: None  # 👈 Headless service
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

---

# StatefulSet for MongoDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: shoppinglist
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        role: backend
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc


