apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppinglist-deployment
  namespace: shoppinglist
spec:
  replicas: 1 # how many pods from this blueprint
  selector:
    matchLabels:
      app: shoppinglist-frontend # How does a controller which pods belong to a Deployment? -> matchLabels!
  template: #template for pods!
    metadata:
      labels:
        app: shoppinglist-frontend # to identify pods of the same type
        role: frontend
    spec:
      containers:
      - name: shoppinglist-frontend #name of the container
        image: shoppinglist-app:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000 # where will it listen
        env: # pass environment variables expected by the app to containers
        - name: MONGODB_URI
          value: "mongodb://mongodb-service.shoppinglist.svc.cluster.local:27017/" # naming: <servicename>.<namespace>.svc.cluster.local:<Port>

---
apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-service
  namespace: shoppinglist

spec:
  selector:
    app: shoppinglist-frontend # has to match the app label of the *template*
  ports:
    - protocol: TCP
      port: 8000 # where it will listen: choose freely
      targetPort: 8000 # where it will send traffic to: match port that is expected
  type: LoadBalancer # this will expose externally
  
  # loadBalancerIP: 203.0.113.25  # To use with pre-allocated static IP. Now it's your job to make it accessible



